'use strict';

module.exports = {
  SONG: {
    CREATE_START: 'CREATE_SONG_START',
    CREATE_FAILURE: 'CREATE_SONG_FAILURE',
    CREATE_SUCCESS: 'CREATE_SONG_SUCCESS',
    FETCH_START: 'FETCH_SONG_START',
    FETCH_FAILURE: 'FETCH_SONG_FAILURE',
    FETCH_SUCCESS: 'FETCH_SONG_SUCCESS'
  },
  SONGS: {
    FETCH_START: 'FETCH_SONGS_START',
    FETCH_FAILURE: 'FETCH_SONGS_FAILURE',
    FETCH_SUCCESS: 'FETCH_SONGS_SUCCESS'
  },
  SONGS_BY_TITLE: {
    FETCH_START: 'FETCH_SONGS_BY_TITLE_START',
    FETCH_FAILURE: 'FETCH_SONGS_BY_TITLE_FAILURE',
    FETCH_SUCCESS: 'FETCH_SONGS_BY_TITLE_SUCCESS'
  },
  SONGS_BY_MUSICIAN: {
    FETCH_START: 'FETCH_SONGS_BY_MUSICIAN_START',
    FETCH_FAILURE: 'FETCH_SONGS_BY_MUSICIAN_FAILURE',
    FETCH_SUCCESS: 'FETCH_SONGS_BY_MUSICIAN_SUCCESS'
  },
  POSITIONS_BY_MUSICIAN: {
    FETCH_START: 'FETCH_POSITIONS_BY_MUSICIAN_START',
    FETCH_FAILURE: 'FETCH_POSITIONS_BY_MUSICIAN_FAILURE',
    FETCH_SUCCESS: 'FETCH_POSITIONS_BY_MUSICIAN_SUCCESS'
  },
  SONG_TITLES: {
    FETCH_TITLE_START: 'FETCH_SONG_TITLE_START',
    FETCH_TITLE_FAILURE: 'FETCH_SONG_TITLE_FAILURE',
    FETCH_TITLE_SUCCESS: 'FETCH_SONG_TITLE_SUCCESS',
    FETCH_START: 'FETCH_SONG_TITLES_START',
    FETCH_FAILURE: 'FETCH_SONG_TITLES_FAILURE',
    FETCH_SUCCESS: 'FETCH_SONG_TITLES_SUCCESS'
  },
  SONG_SEARCH: {
    SEARCH_START: 'SEARCH_SONGS_START',
    SEARCH_FAILURE: 'SEARCH_SONGS_FAILURE',
    SEARCH_SUCCESS: 'SEARCH_SONGS_SUCCESS'
  },
  SEARCH: {
    CHANGED: 'SEARCH_DATA_CHANGED'
  },
  MUSICIAN: {
    FETCH_START: 'FETCH_MUSICIAN_START',
    FETCH_FAILURE: 'FETCH_MUSICIAN_FAILURE',
    FETCH_SUCCESS: 'FETCH_MUSICIAN_SUCCESS'
  }
};
